const skills = [
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/HTML5.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/CSS.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/JS.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/PHP.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/PY.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/C%23.svg",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/NODE.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/BS.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/REACT.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/WP.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/MYSQL.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/PSQL.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/MDB.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/TW.svg",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/LV.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/GH.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/FIGMA.png",
];
const nameSkills = [
	"HTML",
	"CSS",
	"Javascript",
	"PHP",
	"Python",
	"C#",
	"NodeJS",
	"Bootstrap",
	"React",
	"Wordpress",
	"MySQL",
	"PostgreSQL",
	"MongoDB",
	"Tailwind",
	"Laravel",
	"GitHub",
	"Figma",
];

const lagascaPhotos = [
	{
		title: "Proyecto privado en Github, Imágenes del proyecto",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform-img1.png",
		descriptionEN: "Login page.",
		descriptionES: "Página de inicio de sesión.",
		descriptionPT: "Página de login.",
	},
	{
		title: "Barrio la Gasca",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform-img2.png",
		descriptionEN: "Dashboard",
		descriptionES: "Dashboard",
		descriptionPT: "Painel Principal",
	},
	{
		title: "Barrio la Gasca",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform.png",
		descriptionEN: "Users administation.",
		descriptionES: "Administración de usuarios.",
		descriptionPT: "Administração de usuários.",
	},
	{
		title: "Barrio la Gasca",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform-img4.png",
		descriptionEN: "Member administation.",
		descriptionES: "Administración de miembros.",
		descriptionPT: "Administração de membros.",
	},
	{
		title: "Barrio la Gasca",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform-img5.png",
		descriptionEN: "Attendance calendar.",
		descriptionES: "Calendario de asistencias.",
		descriptionPT: "Atendimento.",
	},
	{
		title: "Barrio la Gasca",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform-img6.png",
		descriptionEN: "Whatsapp personalized messages.",
		descriptionES: "Mensajes personalizados de whastapp.",
		descriptionPT: "Mensagens personalizadas do WhatsApp.",
	},
	{
		title: "Barrio la Gasca",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/lagasca-platform-img7.png",
		descriptionEN: "Attendance list and edit by date.",
		descriptionES: "Lista de asistencia y edición por fecha.",
		descriptionPT: "Lista de presença e edição por data.",
	},
];

const cooprogresoPhotos = [
	{
		title: "Proyecto privado en Github, Imágenes del proyecto",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img1.png",
		descriptionEN: "Homepage.",
		descriptionES: "Página de inicio.",
		descriptionPT: "Página inicial.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img2.png",
		descriptionEN: "Login page.",
		descriptionES: "Página de inicio de sesión.",
		descriptionPT: "Página de login.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform.png",
		descriptionEN: "Dashboard Admin.",
		descriptionES: "Dashboard Administrador",
		descriptionPT: "Painel Principal Administrador",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img4.png",
		descriptionEN: "Users administation.",
		descriptionES: "Administración de usuarios.",
		descriptionPT: "Administração de usuários.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img5.png",
		descriptionEN: "Students and certifications.",
		descriptionES: "Estudiantes y certificaciones.",
		descriptionPT: "Estudantes e certificações.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img6.png",
		descriptionEN: "Profile settings.",
		descriptionES: "Configuración de perfil.",
		descriptionPT: "Configurações de perfil.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img7.png",
		descriptionEN: "Dashboard Student.",
		descriptionES: "Dashboard Estudiante.",
		descriptionPT: "Painel Principal Estudante.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img8.png",
		descriptionEN: "Courses platform.",
		descriptionES: "Plataforma de cursos.",
		descriptionPT: "Plataforma de cursos.",
	},
	{
		title: "Cooprogreso",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/cooprogreso-platform-img9.png",
		descriptionEN: "Certification.",
		descriptionES: "Certificación.",
		descriptionPT: "Certificação.",
	},
];

const skillsDesign = [
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/ILL.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/PS.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/PP.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/SKU.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/ARCHICAD.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/ACAD.webp",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/PB.png",
	"https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/icons/FL.png",
];

const nameSkillsDesign = [
	"Photoshop",
	"Illustrador",
	"PremierePro",
	"SketchUp",
	"ArchiCAD",
	"AutoCAD",
	"PolyBoard",
	"FLStudio",
];

const otherPhotos = [
	{
		title: "Del Frutas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/5.png",
		descriptionEN: "Label for powdered panela and fruit tea.",
		descriptionES: "Etiqueta para panela en polvo con sabor de fruta natural",
		descriptionPT: "Etiqueta para panela em pó com sabor de fruta natural",
	},
	{
		title: "Soccer Championship Invitation",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/1.png",
		descriptionEN: "Soccer championship invitation for social media.",
		descriptionES: "Invitación para campeonato de fútbol para redes sociales.",
		descriptionPT: "Convite para campeonato de futebol em redes sociais.",
	},
	{
		title: "Final of Soccer Invitation",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/2.png",
		descriptionEN: "Soccer championship invitation for social media.",
		descriptionES:
			"Invitación para la final de un campeonato de fútbol para redes sociales.",
		descriptionPT:
			"Convite para a final de um campeonato de futebol em redes sociais.",
	},
	{
		title: "Christmas Invitation",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/3.jpg",
		descriptionEN: "Christmas activity invitation for social media.",
		descriptionES: "Invitación para actividad navideña para redes sociales.",
		descriptionPT: "Convite para atividade de Natal em redes sociais.",
	},
	{
		title: "Final of Soccer Invitation 2",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/4.jpg",
		descriptionEN: "Soccer championship invitation for social media.",
		descriptionES:
			"Invitación para la final de un campeonato de fútbol para redes sociales.",
		descriptionPT:
			"Convite para a final de um campeonato de futebol em redes sociais.",
	},
	{
		title: "Flag",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/8.png",
		descriptionEN: "Flag for a neighborhood soccer team.",
		descriptionES: "Bandera para un equipo de fútbol del vecindario.",
		descriptionPT: "Bandeira para um time de futebol do bairro.",
	},
	{
		title: "Birthday",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/9.jpg",
		descriptionEN: "Birthday party invitation for social media.",
		descriptionES: "Invitación de fiesta de cumpleaños para redes sociales.",
		descriptionPT: "Convite de festa de aniversário em redes sociais.",
	},
	{
		title: "Medical prescription",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/10.jpg",
		descriptionEN: "Medical recipe book for a clinic.",
		descriptionES: "Libro de recetas médicas para una clínica.",
		descriptionPT: "Livro de receitas médicas para uma clínica.",
	},
	{
		title: "Label",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/11.png",
		descriptionEN: "Vintage-style label for a bottle.",
		descriptionES: "Etiqueta de estilo vintage para una botella.",
		descriptionPT: "Rótulo em estilo vintage para uma garrafa.",
	},
	{
		title: "Solidary Event",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/12.jpg",
		descriptionEN: "Solidarity lunch for charitable purposes.",
		descriptionES: "Almuerzo solidario con fines benéficos.",
		descriptionPT: "Almoço solidário para fins beneficentes.",
	},
	{
		title: "Elixia",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/13.png",
		descriptionEN: "Logo for a magically styled beverage.",
		descriptionES: "Logotipo para una bebida alcoholica con estilo mágico.",
		descriptionPT: "Logotipo para uma bebida alcoholica com estilo mágico.",
	},
	{
		title: "Duo Esthetic",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/otros/14.png",
		descriptionEN: "Flyer for a beauty salon.",
		descriptionES: "Flyer para un salón de belleza.",
		descriptionPT: "Flyer para um salão de beleza.",
	},
];

const ecoPlagasPhotos = [
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/1.png",
		descriptionEN: "Logo",
		descriptionES: "Logotipo",
		descriptionPT: "Logotipo",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/2.png",
		descriptionEN: "Shield",
		descriptionES: "Escudo",
		descriptionPT: "Escudo",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/3.jpg",
		descriptionEN: "Advertising Social Media 1",
		descriptionES: "Publicidad en redes sociales 1",
		descriptionPT: "Publicidade em redes sociais 1",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/4.jpg",
		descriptionEN: "Advertising Social Media 2",
		descriptionES: "Publicidad en redes sociales 2",
		descriptionPT: "Publicidade em redes sociais 2",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/5.jpg",
		descriptionEN: "Flyer",
		descriptionES: "Volante",
		descriptionPT: "Folheto",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/6.png",
		descriptionEN: "Fridge magnet",
		descriptionES: "Imán de nevera",
		descriptionPT: "Ímã de geladeira",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/7.jpg",
		descriptionEN: "Proforma document",
		descriptionES: "Documento de proforma",
		descriptionPT: "Documento de proforma",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/8.jpg",
		descriptionEN: "Presentation document",
		descriptionES: "Documento de presentación",
		descriptionPT: "Documento de apresentação",
	},
	{
		title: "Eco Plagas",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoPlagas/9.jpg",
		descriptionEN: "Certificate document",
		descriptionES: "Documento de certificado",
		descriptionPT: "Documento de certificado",
	},
];

const queHechoBurguerPhotos = [
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/1.jpg",
		descriptionEN: "Logo",
		descriptionES: "Logotipo",
		descriptionPT: "Logotipo",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/2.png",
		descriptionEN: "Sticker",
		descriptionES: "Calcomanía",
		descriptionPT: "Adesivo",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/3.jpg",
		descriptionEN: "Advertising Social Media 1",
		descriptionES: "Publicidad en redes sociales 1",
		descriptionPT: "Publicidade em redes sociais 1",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/4.jpg",
		descriptionEN: "Advertising Social Media 2",
		descriptionES: "Publicidad en redes sociales 2",
		descriptionPT: "Publicidade em redes sociais 2",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/5.jpg",
		descriptionEN: "Catalogue",
		descriptionES: "Catálogo",
		descriptionPT: "Catálogo",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/6.jpg",
		descriptionEN: "Menu",
		descriptionES: "Menú",
		descriptionPT: "Cardápio",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/7.jpg",
		descriptionEN: "Menu 2",
		descriptionES: "Menú 2",
		descriptionPT: "Cardápio 2",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/8.jpg",
		descriptionEN: "Focus Group Invitation",
		descriptionES: "Invitación a grupo focal",
		descriptionPT: "Convite para grupo focal",
	},
	{
		title: "Que Hecho Burguer",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/queHechoBurguer/9.jpg",
		descriptionEN: "Focus Group Invitation 2",
		descriptionES: "Invitación a grupo focal 2",
		descriptionPT: "Convite para grupo focal 2",
	},
];

const ggBetPhotos = [
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/1.png",
		descriptionEN: "Logo",
		descriptionES: "Logotipo",
		descriptionPT: "Logotipo",
	},
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/2.png",
		descriptionEN: "Poker Chips",
		descriptionES: "Fichas de póker",
		descriptionPT: "Fichas de pôquer",
	},
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/3.jpg",
		descriptionEN: "Advertising Social Media 1",
		descriptionES: "Publicidad en redes sociales 1",
		descriptionPT: "Publicidade em redes sociais 1",
	},
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/4.jpg",
		descriptionEN: "Advertising Social Media 2",
		descriptionES: "Publicidad en redes sociales 2",
		descriptionPT: "Publicidade em redes sociais 2",
	},
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/5.jpg",
		descriptionEN: "Advertising Social Media 3",
		descriptionES: "Publicidad en redes sociales 3",
		descriptionPT: "Publicidade em redes sociais 3",
	},
	// {
	// 	title: "GG Bet",
	// 	img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/6.png",
	// 	descriptionEN: "Advertising Social Media 4",
	// 	descriptionES: "Publicidad en redes sociales 4",
	// 	descriptionPT: "Publicidade em redes sociais 4",
	// },
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/7.jpg",
		descriptionEN: "Advertising Social Media 5",
		descriptionES: "Publicidad en redes sociales 5",
		descriptionPT: "Publicidade em redes sociais 5",
	},
	{
		title: "GG Bet",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ggBet/9.jpg",
		descriptionEN: "Advertising Social Media 7",
		descriptionES: "Publicidad en redes sociales 7",
		descriptionPT: "Publicidade em redes sociais 7",
	},
];

const ecoDomoticHomePhotos = [
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/1.png",
		descriptionEN: "Logo",
		descriptionES: "Logotipo",
		descriptionPT: "Logotipo",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/2.jpg",
		descriptionEN: "Business Card",
		descriptionES: "Tarjeta de presentación",
		descriptionPT: "Cartão de visita",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/3.jpg",
		descriptionEN: "Advertising Social Media 1",
		descriptionES: "Publicidad en redes sociales 1",
		descriptionPT: "Publicidade em redes sociais 1",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/4.jpg",
		descriptionEN: "Proforma Document",
		descriptionES: "Documento Proforma",
		descriptionPT: "Documento Proforma",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/5.jpg",
		descriptionEN: "Catalogue 1",
		descriptionES: "Catálogo 1",
		descriptionPT: "Catálogo 1",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/6.jpg",
		descriptionEN: "Catalogue 2",
		descriptionES: "Catálogo 2",
		descriptionPT: "Catálogo 2",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/7.jpg",
		descriptionEN: "Catalogue 3",
		descriptionES: "Catálogo 3",
		descriptionPT: "Catálogo 3",
	},
	{
		title: "Eco Domotic Home",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/ecoDomoticHome/8.jpg",
		descriptionEN: "Catalogue 4",
		descriptionES: "Catálogo 4",
		descriptionPT: "Catálogo 4",
	},
];

const multiserviciosTecPhotos = [
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/1.png",
		descriptionEN: "Logo",
		descriptionES: "Logotipo",
		descriptionPT: "Logotipo",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/2.jpg",
		descriptionEN: "Business Card",
		descriptionES: "Tarjeta de presentación",
		descriptionPT: "Cartão de visita",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/3.jpg",
		descriptionEN: "Business Card 2-1",
		descriptionES: "Tarjeta de presentación 2-1",
		descriptionPT: "Cartão de visita 2-1",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/4.jpg",
		descriptionEN: "Flyer Service 1",
		descriptionES: "Flyer de servicio 1",
		descriptionPT: "Panfleto de serviço 1",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/5.jpg",
		descriptionEN: "Flyer Service 2",
		descriptionES: "Flyer de servicio 2",
		descriptionPT: "Panfleto de serviço 2",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/6.jpg",
		descriptionEN: "Flyer Service 3",
		descriptionES: "Flyer de servicio 3",
		descriptionPT: "Panfleto de serviço 3",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/7.jpg",
		descriptionEN: "Flyer Service 4",
		descriptionES: "Flyer de servicio 4",
		descriptionPT: "Panfleto de serviço 4",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/8.jpg",
		descriptionEN: "Flyer Service 5",
		descriptionES: "Flyer de servicio 5",
		descriptionPT: "Panfleto de serviço 5",
	},
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/9.jpg",
		descriptionEN: "Flyer Service 6",
		descriptionES: "Flyer de servicio 6",
		descriptionPT: "Panfleto de serviço 6",
	},
	// {
	// 	title: "Multiservicios TEC",
	// 	img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/10.jpg",
	// 	descriptionEN: "Social media Banner",
	// 	descriptionES: "Banner para redes sociales",
	// 	descriptionPT: "Banner para mídias sociais",
	// },
	{
		title: "Multiservicios TEC",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/multiserviciosTec/11.jpg",
		descriptionEN: "Proforma document",
		descriptionES: "Documento Proforma",
		descriptionPT: "Documento Proforma",
	},
];

const vinculoLicoresPhotos = [
	{
		title: "Vinculo Distribuidora",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/vinculoLicores/1.jpg",
		descriptionEN: "Logo 1",
		descriptionES: "Logotipo 1",
		descriptionPT: "Logotipo 1",
	},
	{
		title: "Vinculo Distribuidora",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/vinculoLicores/2.jpg",
		descriptionEN: "Logo 2",
		descriptionES: "Logotipo 2",
		descriptionPT: "Logotipo 2",
	},
	{
		title: "Vinculo Distribuidora",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/vinculoLicores/3.jpg",
		descriptionEN: "Logo 3",
		descriptionES: "Logotipo 3",
		descriptionPT: "Logotipo 3",
	},
	{
		title: "Vinculo Distribuidora",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/vinculoLicores/4.jpg",
		descriptionEN: "Logo Concept",
		descriptionES: "Concepto de logotipo",
		descriptionPT: "Conceito de logotipo",
	},
	{
		title: "Vinculo Distribuidora",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/vinculoLicores/5.jpg",
		descriptionEN: "Color personality",
		descriptionES: "Personalidad del color",
		descriptionPT: "Personalidade das cores",
	},
	{
		title: "Vinculo Distribuidora",
		img: "https://raw.githubusercontent.com/kevinvillajim/Portfolio/main/src/assets/portfolio/Creative/vinculoLicores/6.jpg",
		descriptionEN: "Business card",
		descriptionES: "Tarjeta de presentación",
		descriptionPT: "Cartão de visita",
	},
];

export {
	skills,
	nameSkills,
	skillsDesign,
	nameSkillsDesign,
	otherPhotos,
	ecoPlagasPhotos,
	queHechoBurguerPhotos,
	ggBetPhotos,
	ecoDomoticHomePhotos,
	multiserviciosTecPhotos,
	vinculoLicoresPhotos,
	cooprogresoPhotos,
	lagascaPhotos,
};
